### ISSUE TITLE
alpine based docker can't run the bundled Oasis CLI

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/oasis-web3-gateway#487] opened 2023-12-06 12:31 UTC
```
# ./oasis --help
Error relocating /oasis: __wcsncpy_chk: symbol not found

# ldd oasis
	/lib64/ld-linux-x86-64.so.2 (0x7f87c2905000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f87c2905000)
Error relocating oasis: __snprintf_chk: symbol not found
Error relocating oasis: __vfprintf_chk: symbol not found
Error relocating oasis: __open_2: symbol not found
Error relocating oasis: __pthread_unregister_cancel: symbol not found
Error relocating oasis: __poll_chk: symbol not found
Error relocating oasis: __asprintf_chk: symbol not found
Error relocating oasis: __wcsncpy_chk: symbol not found
Error relocating oasis: __vsnprintf_chk: symbol not found
Error relocating oasis: __fprintf_chk: symbol not found
Error relocating oasis: __pthread_register_cancel: symbol not found
```

**Comment by abukosek** [comment] 2023-12-06 12:33
Hmm, strange.  I installed the glibc compatibility package to make sure it works (otherwise even the node wouldn't start!).
I'll look into this.

**Comment by CedarMist** [comment] 2023-12-06 12:38
Seems like other people have used the `CGO_ENABLED=0` flag when building Go apps to static link. So... bigger executable size.

e.g. https://github.com/k0sproject/k0sctl/pull/273/files

**Comment by abukosek** [comment] 2023-12-06 13:05
This needs to be fixed in oasis-cli -- oasis-node works fine with Alpine's glibc compatibility layer, but oasis-cli breaks, we need to look at what we're doing differently when building the node vs. the cli and fix the cli.

EDIT: I think just adding the `CGO_ENABLED=0` might be enough, no need to fully statically link the executable.

**Comment by abukosek** [comment] 2023-12-06 15:25
> EDIT: I think just adding the `CGO_ENABLED=0` might be enough, no need to fully statically link the executable.

That fixes it, I'll make a PR with a temporary workaround.

**Closed as completed** 2023-12-07 11:43 UTC
Labels: bug, p:2, docker

**Comment by matevz** [comment] 2024-01-08 12:35
Did we discover what was the original issue for the symbol not found errors above? Incompatible glibc version? If the Oasis CLI doesn't work on sapphire-dev/emerald-dev images out of the box, then it may also not work on a number of other distributions.

**Comment by abukosek** [comment] 2024-01-08 14:25
> Did we discover what was the original issue for the symbol not found errors above? Incompatible glibc version? If the Oasis CLI doesn't work on sapphire-dev/emerald-dev images out of the box, then it may also not work on a number of other distributions.

As noted in the PR, the problem is that `CGO_ENABLED=1` is needed for the Ledger stuff to work, but that breaks binary compatibility on anything that doesn't use a recent glibc (e.g. Alpine, which uses musl).
On those platforms, the CLI should be built with `CGO_ENABLED=0`, as we've done in the `sapphire-dev` image and then everything (except Ledger) works normally.
At some point it might be worth researching why Ledger support needs `cgo` and if there's any way to get rid of that.

But in the short term, this is unlikely to affect end-users, since most popular distributions currently use glibc.
